<?php
require 'config.php'; require 'auth.php'; require 'helpers.php';
$search=trim($_GET['q']??'');
if($search!==''){$like='%'.$search.'%';$stmt=$conn->prepare('SELECT f.*,COUNT(c.id) court_count FROM facilities f LEFT JOIN courts c ON c.facility_id=f.id AND c.is_active=1 WHERE f.is_active=1 AND (f.facility_name LIKE ? OR f.location LIKE ?) GROUP BY f.id ORDER BY f.facility_name');$stmt->bind_param('ss',$like,$like);$stmt->execute();$facilities=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);}else{$facilities=$conn->query('SELECT f.*,COUNT(c.id) court_count FROM facilities f LEFT JOIN courts c ON c.facility_id=f.id AND c.is_active=1 WHERE f.is_active=1 GROUP BY f.id ORDER BY f.facility_name')->fetch_all(MYSQLI_ASSOC);}
$myBookings=[];if(current_user_id()){$uid=current_user_id();$stmt=$conn->prepare("SELECT b.id,b.booking_date,b.status,b.total_price,c.court_name,f.facility_name,ts.start_time,ts.end_time FROM bookings b JOIN courts c ON c.id=b.court_id JOIN facilities f ON f.id=c.facility_id JOIN time_slots ts ON ts.id=b.time_slot_id WHERE b.user_id=? ORDER BY b.booking_date DESC,ts.start_time");$stmt->bind_param('i',$uid);$stmt->execute();$myBookings=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);}
$pageTitle='TAR UMT Sports Facility Booking';require 'partials/header.php';
?>
<section class="hero"><h1>Sports Facility Booking</h1><p>Check live availability and reserve campus sports facilities in seconds.</p></section>
<h2>Available Facilities</h2>
<form method="get" class="filter-bar"><label>Search <input type="search" name="q" placeholder="Sport or location..." value="<?= htmlspecialchars($search) ?>"></label><button>Search</button><a class="btn btn-secondary" href="schedule.php">View Schedule</a></form>
<?php if(!$facilities): ?><div class="empty-state"><p>No facilities match your search.</p></div><?php else: ?><div class="card-grid"><?php foreach($facilities as $f): ?><article class="card"><img class="card-thumb" src="<?= htmlspecialchars(entity_image_url($f)) ?>" alt="<?= htmlspecialchars($f['facility_name']) ?>"><h3><?= htmlspecialchars($f['facility_name']) ?></h3><p><?= htmlspecialchars($f['location']) ?></p><p><?= htmlspecialchars($f['description']) ?></p><p><strong>RM<?= number_format($f['price_per_hour'],2) ?>/hour</strong> &middot; <?= (int)$f['court_count'] ?> area(s)</p><a class="btn" href="schedule.php?facility_id=<?= (int)$f['id'] ?>">Check Availability</a></article><?php endforeach; ?></div><?php endif; ?>
<h2>My Bookings</h2>
<?php if(!current_user_id()): ?><div class="card"><p><a href="login.php">Login</a> or <a href="register.php">register</a> to make and manage bookings.</p></div><?php elseif(!$myBookings): ?><div class="empty-state"><p>You have no bookings yet.</p></div><?php else: ?>
<div class="table-wrap"><table><tr><th>Facility</th><th>Area</th><th>Date</th><th>Time</th><th>Status</th><th>Price</th><th>Actions</th></tr><?php foreach($myBookings as $b): ?><tr><td><?= htmlspecialchars($b['facility_name']) ?></td><td><?= htmlspecialchars($b['court_name']) ?></td><td><?= htmlspecialchars(date('d M Y',strtotime($b['booking_date']))) ?></td><td><?= htmlspecialchars(slot_label($b['start_time'],$b['end_time'])) ?></td><td><span class="badge badge-neutral"><?= htmlspecialchars(ucfirst($b['status'])) ?></span></td><td>RM<?= number_format($b['total_price'],2) ?></td><td><a class="btn btn-secondary btn-small" href="confirmation.php?id=<?= (int)$b['id'] ?>">View</a><?php if($b['status']==='confirmed'&&!booking_has_started($b['booking_date'],$b['start_time'])): ?> <a class="btn btn-secondary btn-small" href="edit.php?id=<?= (int)$b['id'] ?>">Edit</a> <form method="post" action="delete.php" style="display:inline" onsubmit="return confirm('Cancel this booking?')"><input type="hidden" name="id" value="<?= (int)$b['id'] ?>"><button class="btn-small btn-danger">Cancel</button></form><?php endif; ?></td></tr><?php endforeach; ?></table></div><?php endif; ?>
<?php require 'partials/footer.php'; ?>

