<?php
require 'config.php';require 'auth.php';require 'helpers.php';$facilityId=(int)($_GET['facility_id']??0);$date=$_GET['date']??date('Y-m-d');if(!valid_date($date)||$date<date('Y-m-d'))$date=date('Y-m-d');$facilities=$conn->query('SELECT id,facility_name FROM facilities WHERE is_active=1 ORDER BY facility_name')->fetch_all(MYSQLI_ASSOC);if(!$facilityId&&$facilities)$facilityId=(int)$facilities[0]['id'];
$stmt=$conn->prepare('SELECT id,court_name FROM courts WHERE facility_id=? AND is_active=1 ORDER BY court_name');$stmt->bind_param('i',$facilityId);$stmt->execute();$courts=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$slots=$conn->query('SELECT * FROM time_slots ORDER BY start_time')->fetch_all(MYSQLI_ASSOC);
$stmt=$conn->prepare("SELECT court_id,time_slot_id,user_id FROM bookings WHERE booking_date=? AND status='confirmed'");$stmt->bind_param('s',$date);$stmt->execute();$booked=[];foreach($stmt->get_result() as $r)$booked[$r['court_id'].'-'.$r['time_slot_id']]=$r;
$stmt=$conn->prepare('SELECT court_id,time_slot_id FROM closures WHERE closure_date=?');$stmt->bind_param('s',$date);$stmt->execute();$closed=[];foreach($stmt->get_result() as $r){if($r['time_slot_id']===null){foreach($slots as $s)$closed[$r['court_id'].'-'.$s['id']]=true;}else $closed[$r['court_id'].'-'.$r['time_slot_id']]=true;}
$pageTitle='Facility Schedule';require 'partials/header.php';?>
<div class="page-header"><h1>Live Facility Schedule</h1><p>Select a sport and date. Available cells open a pre-filled booking form.</p></div><form method="get" class="filter-bar"><label>Facility <select name="facility_id"><?php foreach($facilities as $f): ?><option value="<?= (int)$f['id'] ?>" <?= $facilityId===(int)$f['id']?'selected':'' ?>><?= htmlspecialchars($f['facility_name']) ?></option><?php endforeach; ?></select></label><label>Date <input type="date" name="date" min="<?= date('Y-m-d') ?>" value="<?= htmlspecialchars($date) ?>"></label><button>Show Schedule</button></form>
<?php if(!$courts): ?><div class="empty-state"><p>No active courts are configured.</p></div><?php else: ?><div class="table-wrap"><table><tr><th>Time</th><?php foreach($courts as $c): ?><th><?= htmlspecialchars($c['court_name']) ?></th><?php endforeach; ?></tr><?php foreach($slots as $s): ?><tr><td><?= htmlspecialchars(slot_label($s['start_time'],$s['end_time'])) ?></td><?php foreach($courts as $c):$key=$c['id'].'-'.$s['id'];$past=booking_has_started($date,$s['start_time']);?><td><?php if($past):?><span class="badge badge-neutral">Past</span><?php elseif(isset($closed[$key])):?><span class="badge badge-danger">Closed</span><?php elseif(isset($booked[$key])):?><span class="badge badge-neutral"><?= current_user_id()&&$booked[$key]['user_id']==current_user_id()?'Booked by you':'Booked' ?></span><?php else:?><a class="btn btn-small" href="create.php?court_id=<?= (int)$c['id'] ?>&date=<?= urlencode($date) ?>&slot_id=<?= (int)$s['id'] ?>">Available</a><?php endif;?></td><?php endforeach;?></tr><?php endforeach;?></table></div><?php endif;?><?php require 'partials/footer.php';?>

